"""adding available item quantities

Revision ID: 25523a1f1255
Revises: b49a5d741247
Create Date: 2024-12-25 09:04:32.782738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25523a1f1255'
down_revision = 'b49a5d741247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
