"""added times to Item table

Revision ID: 4042c351c637
Revises: 84e0f6577193
Create Date: 2024-12-21 07:46:29.253848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4042c351c637'
down_revision = '84e0f6577193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('startTime', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('endTime', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('endTime')
        batch_op.drop_column('startTime')

    # ### end Alembic commands ###
